### ISSUE TITLE
Crash on World Creation

### ISSUE THREAD

**Issue by ChloeDawn** [elucent/GravelOres#1]
**Mod version:** [1.0](https://minecraft.curseforge.com/projects/simple-gravel-ores/files/2402251)
**Forge version:** [1.11.2-13.20.0.2261](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2261/forge-1.11.2-13.20.0.2261-changelog.txt)
**Crash report:** [crash-2017-04-03_12.44.04-server.txt](https://gist.github.com/InsomniaKitten/1079a17fdbc9849f32ad6351f8c5285a)

**Comment by elucent** [comment]
Sorry, I derped on something. Shouldn't have been a problem. Anyway, I've just sent CurseForge an updated version and we'll see how quickly they approve it.
