### ISSUE TITLE
crash on 1.11.2

### ISSUE THREAD

**Issue by cursinorock** [elucent/GravelOres#10]
Crash when render.

[crash-2017-08-06_21.12.12-server.txt](https://github.com/elucent/GravelOres/files/1203578/crash-2017-08-06_21.12.12-server.txt)

gravelores-1.1b
1.11.2-forge1.11.2-13.20.1.2429

**Comment by KnightMiner** [comment]
Oh, so version 1.1 had 3 bug fixes, not two like the commit claimed... I'll have a fix up shortly I hope.

**Comment by KnightMiner** [comment]
Fixed in 1.1c, which is up on CurseForge now.
