### ISSUE TITLE
Missing Oretype

### ISSUE THREAD

**Issue by RainbowSaber** [elucent/GravelOres#13]
The Mod is currently missing Bauxite/Aluminium Gravelores
The corresponding oredict is: ore:oreAluminium

**Comment by KnightMiner** [comment]
Huh, what do you know. I assumed it had that.

**Comment by RainbowSaber** [comment]
It is either missing, or doesnt generate when IE Bauxite is the only Aluminium Ore that exists in the environment.

**Comment by KnightMiner** [comment]
Build 1.8 which is on CurseForge now has aluminum gravel ore.
