### ISSUE TITLE
Dropping gold gravel ore onto torch deletes the ore

### ISSUE THREAD

**Issue by mezz** [elucent/GravelOres#14]
I couldn't mine some gold gravel ore with my stone shovel, so I tried to be clever and drop the gravel onto a torch. I expected the blocks to drop, like with regular sand or gravel, but instead the blocks fell and disappeared.

**Comment by KnightMiner** [comment]
This is actually an intended feature to prevent cheesing the mining levels (for instance, getting gold without a iron shovel). It is configurable, see `oreFallingDropItems`.

**Comment by mezz** [comment]
Can you make it so it doesn't break, instead?

**Comment by KnightMiner** [comment]
Not easily, right now I can just use the vanilla entity for all the falling behavior, so I would have to extend and replace the entity and manually determine where the block would land when hitting said block (could be several blocks above the partial block based on what it passes before reaching said block). I might try making it just break and drop the partial block it lands in though.

If it did just land on torches, it would be a bit unexpected behavior anyways, though I guess it would be better that just deleting if something can be done easily.
