### ISSUE TITLE
Modded Ores don't show in JEI

### ISSUE THREAD

**Issue by angelnc1989** [elucent/GravelOres#15]
Minecraft 1.12.2
Forge 14.23.1.2555
Simple Gravel Ores 1.8
JEI 4.8.5.135

![2017-12-10_10 55 45](https://user-images.githubusercontent.com/5382585/33803806-cbca292c-dd98-11e7-9466-a981f3a83810.png)

Modded Ores don't show up in JEI, but they generate in the world.

**Comment by KnightMiner** [comment]
Please explain your issue better. What do you mean by "modded ores"? You mean like copper, aluminum, etc? If so, do those ores exist elsewhere in your pack?

**Comment by angelnc1989** [comment]
Yes, I mean copper, aluminium, lead. I have Immersive Engineering installed, so they are definitly in the pack.

**Comment by KnightMiner** [comment]
I cannot reproduce in my pack. It should be impossible for that to happen since they either generate or they are hidden from creative/JEI

**Comment by KnightMiner** [comment]
@angelnc1989 do you have unidict installed? I've heard it hides blocks with the same oredictionary name from the oredict, and my ore blocks are oredicted like the related ores.

**Comment by angelnc1989** [comment]
That might be it.
