### ISSUE TITLE
[1.12.2] Spawn height

### ISSUE THREAD

**Issue by Draskh** [elucent/GravelOres#16]
I would like to aks if it is possible to add an option to set the spawn height deeper so you can fin Gravel Ores also in caves.

**Comment by Draskh** [comment]
Schould be like that
minh:
maxh:

**Comment by KnightMiner** [comment]
I am going to go with no on this one. The way the gravel ores generator works is it generates ores on the surface of the world (which is pretty easy to find), what you are suggesting would require implementing a second generator to make them generate in caves, which would end up being a regular ore generator as find surfaces in caves is difficult

I suggest you find some mod that lets you control ore generation (I think CoFH core still does) and add the ores into gravel using that.

**Comment by Draskh** [comment]
I will try to use CoFH. 
I tought it was simple to add a spawn height.
