### ISSUE TITLE
Gravel Ores can't be deregistered from Ore Dictionary

### ISSUE THREAD

**Issue by ghost** [elucent/GravelOres#17]
Minecraft version: 1.12.2
Forge Build: 2611
Mod Version: 1.8
CraftTweaker Version: 4.1.2

I'm not sure of the cause, but trying to remove any of the gravel ores from their respective ore dictionary entries fails, and the crafttweaker.log file doesn't give any error messages.

An example line of script that has worked on other items from other mods, but doesn't appear to work for Gravel Ores, is as follows;
\<ore:oreCoal\>.remove(\<gravelores:coal_gravel_ore\>);

Could this please be fixed?

**Comment by KnightMiner** [comment]
Why are you trying to remove them from the oredict? The reason it does not work is probably because the entries have to be registered in postInit, but that is a perfectly valid location to register entries. You will probably notice the same thing with the furnace recipes.

**Comment by ghost** [comment]
Okay, good point. What I'd like to be able to do is disable the ores the mod creates by default.

Edit: woops, wrong button

**Comment by KnightMiner** [comment]
There is a blacklist in the config to disable world generation. Is there a reason you need to disable the block beyond generation?

**Comment by ghost** [comment]
I'm trying to remove it such that it doesn't appear in recipes in JEI, which might be confusing for other players of the pack I'm putting together.

**Comment by KnightMiner** [comment]
There is a JEI config for that. Click the wrench then toggle item hiding mode.

**Comment by ghost** [comment]
Certainly, I've hidden the items from JEI, but they still show up in recipes that utilise their ore dictionary entries (such as the furnace recipe for coal from ore:oreCoal).

Is this an error or oversight on JEI's side, do you think?

**Comment by Garnin** [comment]
have you tried the removeAndHide option with Crafttweaker?

**Comment by KnightMiner** [comment]
Closing as this no longer applies to 1.20, and I no longer support the 1.12 versions.
