### ISSUE TITLE
[Suggestion] description improvement of orePileChance config

### ISSUE THREAD

**Issue by NitroxydeX** [elucent/GravelOres#18]
https://github.com/elucent/GravelOres/blob/9eff439fbc759fbd91902651667a05b16f1989d4/src/main/java/elucent/gravelores/ConfigManager.java#L88

It should mention that lower values means increased chance of generation since it uses a randomNextInt for the chance instead of a procent calculation.

**Comment by KnightMiner** [comment]
Closing as this no longer applies to 1.20, and I no longer support the 1.12 versions.
