### ISSUE TITLE
Config option to disable registration of furnace smelting recipes

### ISSUE THREAD

**Issue by codetaylor** [elucent/GravelOres#19]
I would like to be able to disable the furnace crafting recipes. Because the recipes are registered in post init, using CraftTweaker to remove the recipes does not work.

**Comment by Bucky420** [comment]
yes i need to make the ores only grindable to dust can u make it so we can do this :)

**Comment by KnightMiner** [comment]
Closing as this no longer applies to 1.20, and I no longer support the 1.12 versions.
