### ISSUE TITLE
Digging noise sounds like stone, gravel spawns on ice

### ISSUE THREAD

**Issue by kragnoth** [elucent/GravelOres#2]
As title.  Version 1.1, minecraft verison 1.11.2

The digging noise for the gravel ores is the pickaxe sound for stone.

Gravel is spawning on ice as well.  Maybe only have it spawn on ice if the ice is two thick (i.e. glaciers?)

**Comment by elucent** [comment]
I'll fix the digging sound. Ice never spawns two thick naturally so in a vanilla environment it would basically be disabling gravel ore spawning, so it basically comes down to: would you rather have it spawn on ice or not?

**Comment by kragnoth** [comment]
hmmm... I guess it isn't a huge issue, so I'd just fix the digging sound.

Is it possible to make the all in one tool count as a shovel for the gravel ores without needing to do anything super special on your side?

**Comment by elucent** [comment]
Hmmm...it should be something handled in the class for the AIOT. I'll ask Ellpeck about it -- my gravel ores aren't using anything other than the simple vanilla setHarvestLevel() function, so I'm guessing it's something he'd want to support on his side.

**Comment by kragnoth** [comment]
there is a config option in AA to add it manually, so I'm not sure if you really need to worry about it.

Might I make a suggestion?  Maybe make a config to make the gravel ores only spawn on certain block types that the user enters (by default its everything), I just came across an astral sorcery temple with gravel ore on top of it :D

**Comment by ChloeDawn** [comment]
`*bump*` Pleaseeeee fix the gravel sound, it's been bugging me for months now :v

**Comment by elucent** [comment]
Will be fixed in the 1.12 ver.
