### ISSUE TITLE
Gravel Ores Not Spawning in Ocean Biomes

### ISSUE THREAD

**Issue by Boolyman** [elucent/GravelOres#21]
I am attempting to simply get piles of Diamond Gravel Ore to spawn on the ocean floor.  I setup my config file to blacklist all other biomes and ores except OCEAN and oreDiamond.  And I set the spawn rate of the gravel piles in the Ocean biomes very high (just to test generation), but nothing is generating.  

https://pastebin.com/53ddh5Xj

Appreciate any help you could offer.

**Comment by KnightMiner** [comment]
What world gen are you using? Vanilla or another? In my original testing the ores did spawn in oceans if I removed the biome blacklist for them, so not sure what is going on unless you are just incredibly unlucky

**Comment by KnightMiner** [comment]
Closing for lack of response as this worked in my original testing. My guess is the ocean biome has multiple tags causing it to be blacklisted, you should be able to just empty the whitelist safely.
