### ISSUE TITLE
LoaderExceptionModCrash: Stack can not be invalid

### ISSUE THREAD

**Issue by OrdinatorStouff** [elucent/GravelOres#3]
OreDict errors crashing on startup. I'm about 75% convinced it's because of some other mod interaction but I'm having a hard time tracking it down. I don't know if this is something can be escaped from being caught in gravelores though.

```css
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Gravel Ores (gravelores)
Caused by: java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:440)
	at elucent.gravelores.GravelOres.registerRecipes(GravelOres.java:155)
```

https://pastebin.com/bYkUeS0M

**Comment by elucent** [comment]
Added a check, hopefully this will not happen again.

It should only happen in the first place, though, if someone registers a smelting recipe with an empty input. Which shouldn't happen.

Regardless, it'll be fixed in the next version, which will be for MC 1.12.
