### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [elucent/GravelOres#4]
[crash-2017-06-18_15.17.16-client.txt](https://github.com/elucent/GravelOres/files/1083068/crash-2017-06-18_15.17.16-client.txt)
plz help, thanks.

**Comment by elucent** [comment]
I fixed this in the 1.12 version. Will consider backporting.

**Comment by ghost** [comment]
i will cry if you won't =(

**Comment by KnightMiner** [comment]
As I don't currently plan on backporting to 1.11 and its fixed in the 1.12 version, I think I'll close this. For the record, the issue is ultimately caused by a broken furnace recipe so some other mod can probably fix it on their side.

**Comment by Sunconure11** [comment]
@KnightMiner I rediscovered this after updating a few mods on 1.11.2.

https://pastebin.com/vcEDTG9T

In case any of these mods might be doing something fucky on 1.11.2, these are the mods I have recently updated:

Updated Baubles
Updated BASE
Updated Rustic
Updated Dynamic Surroundings
Updated NetherEx
Updated ModTweaker
Updated Fairylights
Updated Ceramics
Updated Chest Transporter
Updated Nutrition
Updated Lapis Stays in the Enchanting Table

**Comment by Sunconure11** [comment]
@KnightMiner It's an issue with your own mod, Ceramics.

**Comment by KnightMiner** [comment]
Well, I reconsidered and released a quick patch for 1.11.2 to fix this. It seems Elucent never pushed the code for version 1.1 so I had to refix those bugs on the 1.11 branch, so hopfully it runs like 1.1 did but with this fix. Its on Curseforge now as 1.1b

**Comment by ghost** [comment]
(i'm on 1.12 now)
