### ISSUE TITLE
Can't do anything with the gravel ore?

### ISSUE THREAD

**Issue by RayzoRayy** [elucent/GravelOres#6]
I can't seem to be able to smelt the gravel ores into ingots, or anything for that matter, how exactly do I turn the graven ores into the ingot form? Is this a bug, or am I just missing something?

Gravel Ores version: 1.6
Forge Version: 14.21.1.2443
Mc Version 1.12

**Comment by KnightMiner** [comment]
Hmm, the function exists to add the recipes, but testing it shows its not working. Let me look into why its broken

**Comment by sorc23** [comment]
I am having the same issues with the same versions

**Comment by KnightMiner** [comment]
Oh, thats why. Seems the oredict tags are never added to the ores. I'll have a fix for it later today hopefully

**Comment by RayzoRayy** [comment]
Awesome, thanks.

**Comment by KnightMiner** [comment]
Fixed in version 1.7 which is now on CurseForge.
