### ISSUE TITLE
[1.12] Modded Ores are not added

### ISSUE THREAD

**Issue by angelnc1989** [elucent/GravelOres#7]
Minecraft 1.12
Forge 14.21.1.2443
Gravel Ores 1.6

Even though I have ImmersiveEngineering which adds Copper, Lead, Silver and Nickel those are not added as Gravel Ores. They are not blacklisted either.

**Comment by KnightMiner** [comment]
Yeah, I kinda suspected this would be the case, but forgot to check. Oredictionary stuff changed so I'll have to move some checks to postInit

**Comment by KnightMiner** [comment]
Fixed in version 1.7 which is now on CurseForge.
