### ISSUE TITLE
[Request] Biome blacklist

### ISSUE THREAD

**Issue by ghost** [elucent/GravelOres#8]
Please add a biome blacklist to the config to make it possible to prevent the ores from occuring in certain biomes completely.

**Comment by KnightMiner** [comment]
Hmm, I can look into this. Are there any specific Biomes that are causing issues?

**Comment by ghost** [comment]
No real issues. I want to blacklist deserts, beaches and the biomes from the Defiled Lands mod for aesthetic reasons.

**Comment by KnightMiner** [comment]
Version 1.8 on CurseForge now features a biome blacklist and whitelist. It uses BiomeDictionary types rather than Biome IDs to make it more compatible, so for your uses you just need to add `DESERT`, `BEACH`, and whatever type Defiled Lands uses for its biomes to the blacklist.
