### ISSUE TITLE
[SUGGESTION] Uranium Gravel Ore?

### ISSUE THREAD

**Issue by Sunconure11** [elucent/GravelOres#9]
Plenty of mods use uranium. Would it be possible to add a uranium gravel ore?

**Comment by KnightMiner** [comment]
I personally don't feel uranium fits as a gravel ore just as its intended to be a rarer ore. I would like to implement a system for users to add their own arbitrary ores though, so the ability to add yourself might come in.

**Comment by KnightMiner** [comment]
Version 1.8 on CurseForge has a config to add your own ores. Config string will look something like the following:

* `uranium:22DD22:2:3.0`

Just note you need to localize it as well, as there was no way I could dynamically do that.
